Error handling
Icinga/icingadb pull request #289
Opened 2021-05-31 12:21 UTC by lippserd

2021-06-08 15:26 UTC, julianbrost reviewed
Just what I've noticed so far from going over the code once.

2021-06-08 15:26 UTC, julianbrost commented on internal/internal.go
> +	return errors.Wrap(err, "can't perform "+q)
This could use a `%q` format string to get a nice quoted query.

2021-06-08 15:26 UTC, julianbrost commented on internal/internal.go
> +	return errors.Wrapf(err, "can't unmarshal JSON '%s' (%#v) into %T", data, data, v)
`%q` instead of `'%s'`. Also, why is `data` logged twice?

2021-06-08 15:26 UTC, julianbrost commented on pkg/icingadb/overdue/sync.go
> +	_, _ = cmd.Result() // Error is handled by icingaredis.WrapCmdErr().
Maybe have a function that both calls `.Result()` and performs the error wrapping? Would avoid having to explain why there's no error handling here.

2021-06-08 15:26 UTC, julianbrost commented on pkg/icingaredis/v1/stats_message.go
> +	return nil, errors.Errorf("bad message %#v. %s missing", m, "IcingaApplication")
Why not just inline the hardcoded string constant parameter into the format string?

2021-06-08 15:26 UTC, julianbrost commented on pkg/icingaredis/v1/stats_message.go
> +	return nil, errors.Errorf("bad message %#v. %s missing", m, "timestamp")
Same here.

2021-06-08 15:26 UTC, julianbrost commented on pkg/types/bool.go
> +		return errors.Wrapf(err, "can't parse '%s' into uint64", text)
`%q` instead of `'%s'`

2021-06-08 15:26 UTC, julianbrost commented on pkg/types/comment_type.go
> +		return errors.Wrapf(err, "can't parse '%s' into uint64", text)
`%q` instead of `'%s'`

2021-06-08 15:26 UTC, julianbrost commented on pkg/types/float.go
> +		return errors.Wrapf(err, "can't parse '%s' into float64", text)
`%q` instead of `'%s'`

2021-06-14 14:08 UTC, julianbrost requested changes

2021-06-14 14:08 UTC, julianbrost commented on pkg/types/binary.go
> +		return errors.Wrapf(err, "can't decode hex %q into %T", text, b)
`%T` of `b` will always be `[]byte`, so I think there's little value in adding this to the message.

2021-06-14 14:08 UTC, julianbrost commented on internal/internal.go
> +func MarshalJSON(v interface{}) ([]byte, error) {
Why this but no `UnmarshalJSON()`?

2021-06-14 15:15 UTC, lippserd commented on internal/internal.go
> +func CantUnmarshalYAML(err error, data interface{}) error {
That makes sense. I don't think there is any other way to access the raw YAML other than adding it to the error in `FromYAMLFile`. But the error message contains the path to the file, which should be enough:

> can't parse YAML file ./config.yml: can't unmarshal YAML into *config.Database: yaml: unmarshal errors:
  line 3: mapping key "host" already defined at line 2

Also, I don't think it's a good idea to post passwords in logs.

2021-06-14 15:16 UTC, lippserd commented on pkg/config/redis.go
> +		}
Nice, good catch! I will address all the places where we can unconditionally call `errors.Wrap *`.

2021-06-14 15:16 UTC, lippserd commented on pkg/icingaredis/error_handling.go
> +type ErrorHandling struct{}
`WrapErrors` sounds good to me.

2021-06-14 15:18 UTC, lippserd commented on internal/internal.go
> +func MarshalJSON(v interface{}) ([]byte, error) {
Good question 😆 I'll add it.

2021-06-15 06:52 UTC, julianbrost commented on internal/internal.go
> +func CantUnmarshalYAML(err error, data interface{}) error {
> Also, I don't think it's a good idea to post passwords in logs

Good point, I just noticed that it's inconsistent with the functions for JSON. The JSON could also contain sensitive information though (mainly custom vars, like SNMP credentials for example).

2021-06-18 07:27 UTC, lippserd commented on internal/internal.go
> +func CantUnmarshalYAML(err error, data interface{}) error {
I also removed it JSON contents from the error.

2021-06-21 12:10 UTC, julianbrost approved these changes

2021-06-21 15:58 UTC, merged