Code quality
Icinga/icingadb pull request #299
Opened 2021-06-10 12:37 UTC by lippserd

2021-06-24 09:17 UTC, julianbrost requested changes
The remaining comments in `pkg/icingadb/db.go` (line 378 and below) could probably all be a bit more verbose. Didn't want to comment each on its own.

2021-06-24 09:17 UTC, julianbrost commented on pkg/icingaredis/utils.go
> +// SetChecksums concurrently concurrently streams from the given entities and sets their checksums using the specified map and streams the results on a returned channel.
Concurrency² for even more speed?

2021-07-13 15:33 UTC, julianbrost requested changes

2021-07-13 15:33 UTC, julianbrost commented on pkg/icingaredis/utils.go
> +// CreateEntities streams and creates entities from the given Redis field value paris using the specified factory function, and streams them on a returned channel.
Typo in pairs

2021-07-13 15:37 UTC, julianbrost commented on pkg/icingadb/db.go
> +	return db.NamedBulkExec(ctx, stmt, utils.Min(1<<14/placeholders, 1<<10), sem, forward, nil)
Created a review for that in the actual PR for this change: https://github.com/Icinga/icingadb/pull/312#pullrequestreview-705350715

2021-07-13 18:26 UTC, lippserd commented on pkg/driver/driver.go
> +	_ = mysql.SetLogger(mysqlLogger(func(v ...interface{}) { logger.Debug(v) }))
True!

2021-07-13 18:34 UTC, lippserd commented on pkg/icingadb/db.go
> +// Entities for which the query ran successfully will be streamed on the succeeded channel.
Your assumption is correct, although these are implementation details and should not be relevant in the docs. So what exactly is difficult to understand? Should I add something like "Derives and executes a new query with placeholders  automatically expanded and replaced with the appropriate DB driver's bindvar type."?

2021-07-13 18:34 UTC, lippserd commented on pkg/icingadb/db.go
> +// executes a new query for each entity in the set of arguments in a new transaction,
Yep.

2021-07-14 07:42 UTC, julianbrost commented on pkg/icingadb/db.go
> +// Entities for which the query ran successfully will be streamed on the succeeded channel.
I don't see a generic way to take any query and execute it on multiple sets of arguments except just running the query multiple times. But that's what `NamedBulkExecTx` does and this function performs no fallback to that one.

So there has to be some restriction on the types of queries this function can handle.

I do understand that this function just inherits its behavior from [`sqlx.DB.NamedExecContext()`](https://pkg.go.dev/github.com/jmoiron/sqlx#DB.NamedExecContext) but I also find that documentation lacking. At least to me, it's not clear that you're even supposed to pass a slice as `arg`.

2021-08-06 08:47 UTC, lippserd commented
Removed some commits here and created #340 and #341 as these changes were not really related to code quality.

2021-08-06 13:13 UTC, julianbrost approved these changes

2021-08-09 08:41 UTC, merged