Fix SEGV due to empty config
Icinga/icingadb pull request #303
Opened 2021-06-29 14:19 UTC by Al2Klimov

2021-06-29 14:20 UTC, Al2Klimov commented
Tested with the config `{}` which may be emitted by our entrypoint.

2021-06-30 19:29 UTC, lippserd requested changes
Still does not work for `---`.

2021-07-07 09:27 UTC, julianbrost approved these changes

2021-07-08 08:50 UTC, lippserd approved these changes

2021-07-08 08:50 UTC, merged