Bulk statement size
Icinga/icingadb pull request #312
Opened 2021-07-13 12:51 UTC by lippserd

2021-07-13 15:37 UTC, julianbrost reviewed
`1<<14` could be made a named constant like `stmtMaxPlaceholders` with a comment stating the source for that number or some explanation why it was chosen. Seems like the limit imposed by MySQL would be `1<<16`.

2021-08-03 07:04 UTC, lippserd commented
> `1<<14` could be made a named constant like `stmtMaxPlaceholders` with a comment stating the source for that number or some explanation why it was chosen. Seems like the limit imposed by MySQL would be `1<<16`.

I've documented the options and made them configurable too.

2021-08-03 13:41 UTC, julianbrost requested changes

2021-08-03 13:41 UTC, julianbrost commented on pkg/icingadb/db.go
> +	return db.NamedBulkExec(ctx, stmt, db.options.MaxPlaceholdersPerStatement/placeholders, sem, forward, nil)
Could become 0 if a small value is set. There's no documentation on what the required minimum would be and even if it was documented, it potentially would have to be updated when we add columns and so on. So maybe go with something like `max(maxPlaceholders/placeholders, 1)` here and in the other places?

2021-08-04 10:34 UTC, julianbrost approved these changes

2021-08-04 22:40 UTC, merged