Downtime: Add parent_downtime_id
Icinga/icingadb pull request #323
Opened 2021-07-22 15:47 UTC by N-o-X

This PR adds the downtime attribute `parent_downtime_id` added to Icinga 2 with https://github.com/Icinga/icinga2/pull/8913 to Icinga DB.

2021-07-22 19:40 UTC, lippserd commented
Also with # 301 in mind, are `trigger_by_id`, `parent_downtime_id` and `scheduled_by` mutually exclusive or could two or all of them be set?

2021-07-23 11:59 UTC, N-o-X commented
As we already found out in our meeting a few hours ago, `trigger_by_id` and `scheduled_by` will both be set, when using `child_options` in a `ScheduledDowntime`.

2021-08-03 06:51 UTC, lippserd requested changes
Even if the other columns don't have a meaningful comment at the moment, it would be good if the comment for `parent_id` describes what the column represents.

2021-08-09 11:32 UTC, N-o-X commented
> Even if the other columns don't have a meaningful comment at the moment, it would be good if the comment for `parent_id` describes what the column represents.

I'd create a separate PR to add descriptions for all 3 columns.

2021-08-09 11:34 UTC, N-o-X commented
@cla-bot check

2021-08-09 11:41 UTC, lippserd approved these changes

2021-08-09 11:43 UTC, merged