Fix data races
Icinga/icingadb pull request #365
Opened 2021-09-20 07:27 UTC by lippserd

This PR addresses the following data races that can occur if an ongoing config sync is canceled:

`counter.go`:

```
WARNING: DATA RACE
Read at 0x00c03212e4a0 by goroutine 786:
  github.com/icinga/icingadb/pkg/icingaredis.(*Client).HYield.func1.1()
      /Users/elippmann/Workspace/icingadb/pkg/icingaredis/client.go:57 +0xa4
  github.com/icinga/icingadb/pkg/utils.Timed()
      /Users/elippmann/Workspace/icingadb/pkg/utils/utils.go:75 +0x61
  github.com/icinga/icingadb/pkg/icingaredis.(*Client).HYield.func1()
      /Users/elippmann/Workspace/icingadb/pkg/icingaredis/client.go:71 +0x51f
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /Users/elippmann/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x94

Previous write at 0x00c03212e4a0 by goroutine 986:
  sync/atomic.AddInt64()
      /usr/local/Cellar/go/1.16.5/libexec/src/runtime/race_amd64.s:300 +0xb
  github.com/icinga/icingadb/pkg/com.(*Counter).Add()
      /Users/elippmann/Workspace/icingadb/pkg/com/counter.go:10 +0xa4
  github.com/icinga/icingadb/pkg/com.(*Counter).Inc()
      /Users/elippmann/Workspace/icingadb/pkg/com/counter.go:15 +0x89
  github.com/icinga/icingadb/pkg/icingaredis.(*Client).HYield.func1.2.1()
      /Users/elippmann/Workspace/icingadb/pkg/icingaredis/client.go:82 +0x88
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /Users/elippmann/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x94

Goroutine 786 (running) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /Users/elippmann/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x73
  github.com/icinga/icingadb/pkg/icingaredis.(*Client).HYield()
      /Users/elippmann/Workspace/icingadb/pkg/icingaredis/client.go:52 +0x317
  github.com/icinga/icingadb/pkg/icingaredis.Client.YieldAll()
      /Users/elippmann/Workspace/icingadb/pkg/icingaredis/client.go:191 +0x1cb
  github.com/icinga/icingadb/pkg/icingadb.Sync.Sync()
...
```

`client.go`
```
WARNING: DATA RACE
Write at 0x00c0002018d0 by goroutine 307:
  runtime.closechan()
      /usr/local/Cellar/go/1.16.5/libexec/src/runtime/chan.go:355 +0x0
redis level handler called  github.com/icinga/icingadb/pkg/icingaredis.(*Client).HYield.func1()
      /Users/elippmann/Workspace/icingadb/pkg/icingaredis/client.go:71 +0x51f
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /Users/elippmann/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x94

Previous read at 0x00c0002018d0 by goroutine 266:
  runtime.chansend()
      /usr/local/Cellar/go/1.16.5/libexec/src/runtime/chan.go:158 +0x0
  github.com/icinga/icingadb/pkg/icingaredis.(*Client).HYield.func1.2.1()
      /Users/elippmann/Workspace/icingadb/pkg/icingaredis/client.go:78 +0x24c
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /Users/elippmann/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x94

Goroutine 307 (running) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /Users/elippmann/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x73
  github.com/icinga/icingadb/pkg/icingaredis.(*Client).HYield()
      /Users/elippmann/Workspace/icingadb/pkg/icingaredis/client.go:52 +0x317
  github.com/icinga/icingadb/pkg/icingaredis.Client.YieldAll()
      /Users/elippmann/Workspace/icingadb/pkg/icingaredis/client.go:191 +0x1cb
  github.com/icinga/icingadb/pkg/icingadb.Sync.Sync()
      /User2021-07-15T13:32:50.562+0200	INFO	redis	Fetched 4021 elements of icinga:notification:user in 1.946620081s
s/elippmann/Workspace/icingadb/pkg/icingadb/sync.go:75 +0x25a
  github.com/icinga/icingadb/pkg/icingadb.Sync.SyncAfterDump()
      /Users/elippmann/Workspace/icingadb/pkg/icingadb/sync.go:61 +0xacd
  main.run.func2.5()
      /Users/elippmann/Workspace/icingadb/cmd/icingadb/main.go:238 +0x29b
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /Users/elippmann/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x94

Goroutine 266 (running) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /Users/elippmann/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x73
  github.com/icinga/icingadb/pkg/icingaredis.(*Client).HYield.func1()
      /Users/elippmann/Workspace/icingadb/pkg/icingaredis/client.go:74 +0x492
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /Users/elippmann/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x94
...
```

```
panic: send on closed channel

goroutine 1469 [running]:
github.com/icinga/icingadb/pkg/icingaredis.(*Client).HYield.func1.2.1(0xc00183ef50, 0x0)
	/Users/elippmann/Workspace/icingadb/pkg/icingaredis/client.go:77 +0x2a7
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0015a7ce0, 0xc000250140)
	/Users/elippmann/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x95
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/elippmann/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x74
exit status 2

WARNING: DATA RACE
Write at 0x00c000218d30 by goroutine 839:
  runtime.closechan()
      /usr/local/Cellar/go/1.16.5/libexec/src/runtime/chan.go:355 +0x0
  github.com/icinga/icingadb/pkg/icingaredis.(*Client).HYield.func1()
      /Users/elippmann/Workspace/icingadb/pkg/icingaredis/client.go:71 +0x51f
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /Users/elippmann/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x94

Previous read at 0x00c000218d30 by goroutine 835:
  runtime.chansend()
      /usr/local/Cellar/go/1.16.5/libexec/src/runtime/chan.go:158 +0x0
  github.com/icinga/icingadb/pkg/icingaredis.(*Client).HYield.func1.2.1()
      /Users/elippmann/Workspace/icingadb/pkg/icingaredis/client.go:78 +0x24c
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /Users/elippmann/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x94

Goroutine 839 (running) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /Users/elippmann/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x73
  github.com/icinga/icingadb/pkg/ici2021-07-16T09:22:20.288+0200	DEBUG	icingadb/delta.go:92	Synced 10501 desired elements of type NotificationUser in 3.691849548s
ngaredis.(*Client).HYield()
      /Users/elippmann/Workspace/icingadb/pkg/icingaredis/client.go:52 +0x317
  github.com/icinga/icingadb/pkg/icingaredis.Client.YieldAll()
      /Users/elippmann/Workspace/icingadb/pkg/icingaredis/client.go:191 +0x1cb
  github.com/icinga/icingadb/pkg/icingadb.Sync.Sync()
      /Users/elippmann/Workspace/icingadb/pkg/icingadb/sync.go:75 +0x25a
  github.com/icinga/icingadb/pkg/icingadb.Sync.SyncAfterDump()
      /Users/elippmann/Workspace/icingadb/pkg/icingadb/sync.go:61 +0xacd
  main.run.func1.5()
      /Users/elippmann/Workspace/icingadb/cmd/icingadb/main.go:140 +0x29b
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /Users/elippmann/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x94

Goroutine 835 (running) created at:
  golang.org/x/sync/errgroup.(*Group).Go()
      /Users/elippmann/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x73
  github.com/icinga/icingadb/pkg/icingaredis.(*Client).HYield.func1()
      /Users/elippmann/Workspace/icingadb/pkg/icingaredis/client.go:74 +0x492
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /Users/elippmann/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x9
...
```

2021-09-20 11:20 UTC, julianbrost commented
> ```
> github.com/icinga/icingadb/pkg/icingaredis.(*Client).HYield.func1.2.1(0xc00183ef50, 0x0)
> 	/Users/elippmann/Workspace/icingadb/pkg/icingaredis/client.go:77 +0x2a7
> ```

From which version is that? On the base commit of this branch, line 77 is an empty line. But I presume it's that one now as it's the only send in that function: https://github.com/Icinga/icingadb/blob/47bc17f7d8b4da8122670d4c7f8971ce58b948f2/pkg/icingaredis/client.go#L96

2021-09-20 11:34 UTC, lippserd commented
> From which version is that?

I don't remember exactly. I had these lines in my notes. But yes, it all has to do with the sends to the pairs channel.

2021-09-20 12:02 UTC, julianbrost requested changes
I believe `HMYield` could still observe a send to closed channel condition.

The issue isn't about nesting of errgroups but instead that there are code paths that return and trigger the `defer close(pairs)` without waiting for the errgroup first, namely the error handling for `c.HScan()` and `sem.Acquire()`.

Doing the following should also fix the race while keeping the concurrency as is:
```go
defer func() {
    g.Wait()
    close(pairs)
}()
```

Important detail: even if a goroutine returns an error, `Wait()` waits for all other goroutines to complete, so calling `g.Wait()` ensures that there is nothing that would send to the channel anymore.

For completeness, the code path that would still trigger the send to closed channel (also explains what happens when that panic occurs on the current master):
1. Outer context in canceled.
2. `sem.Acquire()` returns due to context being canceled: https://github.com/Icinga/icingadb/blob/dcc73c909d4ce0c02ac966351b9a71c45b9bdd23/pkg/icingaredis/client.go#L125-L127
3. `defer close(pairs)` is triggered by that return: https://github.com/Icinga/icingadb/blob/dcc73c909d4ce0c02ac966351b9a71c45b9bdd23/pkg/icingaredis/client.go#L116
4. One of the remaining goroutines tries to send to `pairs` (as there's no `g.Wait()` on this code path): https://github.com/Icinga/icingadb/blob/dcc73c909d4ce0c02ac966351b9a71c45b9bdd23/pkg/icingaredis/client.go#L147-L150

2021-09-20 12:57 UTC, lippserd commented
> The issue isn't about nesting of errgroups but instead that there are code paths that return and trigger the `defer close(pairs)` without waiting for the errgroup first, namely the error handling for `c.HScan()` and `sem.Acquire()`.

That is true and I'm aware that the nested errgroups are not the problem. I just removed them for reduced complexity and forgot about the `sem.Acquire()` path. Thanks for the heads up! I would call `g.Wait()` before returning the error from the `sem.Acquire()` as this makes it dead obvious that it is a not so common code path/usage of `g.Wait()`.

2021-09-20 13:20 UTC, julianbrost reviewed
> That is true and I'm aware that the nested errgroups are not the problem.

Ok, I read the commit messages as if that might have been the issue.

> I would call `g.Wait()` before returning the error from the `sem.Acquire()` as this makes it dead obvious that it is a not so common code path/usage of `g.Wait()`.

I think having it in the defer handler makes it more obvious to why it's done (i.e. wait so that the next line can safely close the channel) while adding it before the return statement separates these two operations and also means that we have to manually ensure that this on done on each return path (which is what `defer` exists for). Yes, `Wait()` is called twice on one code path, but I don't see an issue with that. One call to obtain the error and another one to ensure that the channel can be closed safely.

2021-09-20 13:20 UTC, julianbrost commented on pkg/icingaredis/client.go
>  	pairs := make(chan HPair)
Then I'd at least make this channel buffered so that the next HSCAN call isn't waiting for the result of the previous one being processed.

2021-09-20 13:20 UTC, julianbrost commented on pkg/icingaredis/client.go
>  	pairs := make(chan HPair)
(This on is probably fine to keep unbuffered as there's some implicit buffering by using multiple goroutines.)

2021-09-23 09:19 UTC, julianbrost requested changes

2021-09-23 09:19 UTC, julianbrost commented on pkg/icingaredis/client.go
> +		var cnt com.Counter
Can be made a simple `uint64` as there's no more concurrent access.

2021-09-23 10:32 UTC, julianbrost approved these changes

2021-09-23 10:32 UTC, merged