RuntimeUpdates#Sync(): force FIFO for config updates
Icinga/icingadb pull request #394
Opened 2021-10-20 14:09 UTC by Al2Klimov

so they don't interfer.

2021-11-02 14:33 UTC, julianbrost requested changes
Oh, and as I've just noticed, this needs a rebase now.

2021-11-03 10:32 UTC, Al2Klimov commented
## Speed up by

* #400

2021-11-03 10:38 UTC, julianbrost commented
> ## Speed up by

What's that supposed to mean?

2021-11-03 11:01 UTC, Al2Klimov commented
That it's not tech.ly blocking, but it would make my life a lot easier here.

2021-11-11 11:13 UTC, julianbrost requested changes
In general, I think the code would be simpler if the goroutine that does `counter.Inc()` would simply forward the entity to a second channel if and only if `!allowParallel` so that that second channel can then be used to synchronize the insertion order. Then it would also be clear when which channel has to be closed where.

2021-11-11 11:13 UTC, julianbrost commented on pkg/icingadb/runtime_updates.go
> +				}
This operation is only safe if there's no concurrent write/close action on the same channel.

2021-11-11 11:13 UTC, julianbrost commented on pkg/icingadb/runtime_updates.go
> +				}
But here is the same operation again.

2021-11-11 11:13 UTC, julianbrost commented on pkg/icingadb/runtime_updates.go
> +			deletedLog = deleted
And if `allowParallel`, then `upsertedLog = upserted`, so both might observe that the channel is not yet closed and attempt to close it resulting in a panic.

2021-11-11 13:09 UTC, julianbrost requested changes
I think https://github.com/Icinga/icingadb/pull/394/commits/a90dc7a4b28f3cdc38097ae99bc785f1a19188de shouldn't be in this PR (for now this is the only change request, the inline comment is only a question).

2021-11-12 10:41 UTC, julianbrost requested changes
Apart from the outdated comments: tested and approved.

2021-11-12 10:41 UTC, julianbrost commented on pkg/com/bulker.go
> +// but without the overhead of handling different values for 1 and 0.
Outdated comment, `NewBulker` only takes 3 arguments.

2021-11-12 10:41 UTC, julianbrost commented on pkg/com/entity_bulker.go
> +// but without the overhead of handling different values for 1 and 0.
Outdated comment, `NewEntityBulker` only takes 3 arguments.

2021-11-12 11:46 UTC, julianbrost approved these changes

2021-11-12 11:56 UTC, merged