PostgreSQL: Support LIKE for integer columns
Icinga/icingadb pull request #461
Opened 2022-04-11 09:57 UTC by lippserd

2022-04-11 12:27 UTC, yhabteab reviewed
As it is, pgsql throws an error that the uint operator isn't unique, as the two domains (`uint`, `biguint`) have the same underlying data type. Hence just using three operators (`smallint`, `int`, `bigint`) are sufficient. With this I tested it and it works great.

2022-04-12 14:15 UTC, yhabteab reviewed
Requesting for a `Host/Service Check Interval=5.5` produces the following result:

<img width="874" alt="Bildschirmfoto 2022-04-12 um 16 06 44" src="https://user-images.githubusercontent.com/57616252/162982394-6f055233-d538-42f8-be59-67ff246eb5ba.png">

2022-04-12 14:42 UTC, julianbrost commented
Can't web just always use `x::text LIKE y` instead of `x LIKE y` in the queries?

2022-04-22 12:43 UTC, julianbrost commented
For completeness as we discussed this somewhere else: `x::text` wouldn't work properly for columns of type `citext`.

2022-04-29 07:01 UTC, nilmerg commented on schema/pgsql/schema.sql
> +   This fails for PostgreSQL as it cannot match numbers to text. To support this,
This is misleading. DB Web doesn't just pass numbers as text, it's rather passing numbers encapsulated by wildcards (e.g. `%4%`) which is only possible by passing text. The solution in DB Web also is not by offering different operators but by disallowing wildcards for integer columns.

2022-05-04 14:26 UTC, lippserd commented
> Requesting for a `Host/Service Check Interval=5.5` produces the following result:
> 
> <img alt="Bildschirmfoto 2022-04-12 um 16 06 44" width="874" src="https://user-images.githubusercontent.com/57616252/162982394-6f055233-d538-42f8-be59-67ff246eb5ba.png">

This cannot be fixed by operator overloading, but requires column type support in Icinga DB Web.

2022-05-05 09:02 UTC, julianbrost commented
Is PostgreSQL support in icingadb-web in a state where it's meaningful for me to use that for testing this?

Btw (before I tested anything): what happens if you filter for `flapping_threshold_low` (on of the few `float` columns we have)?

2022-05-05 10:03 UTC, lippserd commented
> Is PostgreSQL support in icingadb-web in a state where it's meaningful for me to use that for testing this?

Yes. You can also test this by running `SELECT 25::biguint LIKE '%5%';` or `SELECT 25::float LIKE '%5%';` and so on.

> Btw (before I tested anything): what happens if you filter for `flapping_threshold_low` (on of the few `float` columns we have)?

Good point. Fixed.

2022-05-05 13:55 UTC, julianbrost commented
Trying LIKE for the different types we use in the schema not yet mentioned in this PR:
* `text`, `citext`, `varchar`: works out of the box as you'd expect.
* `bytea` (and `byteaN`): works out of the box, probably of limited usefulness, but not an error (users shouldn't typically filter on these raw values anyways but rather on the referenced objects).
* `enum` (including the custom types like `boolenum`): haven't tested with icingadb-web + PostgreSQL, but with MySQL it offers me to filter on these columns and doing this manually in PostgreSQL with LIKE yields an error, so same problem there as well?
    ```
    icingadb=# SELECT * FROM host WHERE event_handler_enabled LIKE '%42%';
    ERROR:  operator does not exist: boolenum ~~ unknown
    LINE 1: SELECT * FROM host WHERE event_handler_enabled LIKE '%42%';
    ```

2022-05-09 15:24 UTC, julianbrost commented
I can't follow. Doing the very same operator dance seems to work for enum types as well:
```
icingadb=# CREATE FUNCTION boolenumliketext(boolenum, text) RETURNS boolean
  LANGUAGE SQL
  IMMUTABLE
  PARALLEL SAFE
  RETURN $1::TEXT LIKE $2;
CREATE OPERATOR ~~ (LEFTARG=boolenum, RIGHTARG=text, PROCEDURE=boolenumliketext);
CREATE FUNCTION
CREATE OPERATOR
icingadb=# SELECT * FROM host WHERE event_handler_enabled LIKE '%42%';
(0 rows)
```

2022-05-09 15:45 UTC, lippserd commented
> I can't follow. Doing the very same operator dance seems to work for enum types as well:

Strange. I will do the tests again.

2022-05-12 07:33 UTC, lippserd commented
> > I can't follow. Doing the very same operator dance seems to work for enum types as well:
> 
> Strange. I will do the tests again.

Found a catch-all solution.

2022-05-12 13:42 UTC, julianbrost reviewed
Nice, so now this depends on https://github.com/Icinga/icinga-testing/pull/21 (in particular https://github.com/Icinga/icinga-testing/pull/21/commits/01aa6d63dfa0c863b21fb3d0618692e861caa05f) for the tests.

Side note: my personal preference would be putting `AS $$...$$` last (but you don't have to change that).

2022-05-13 10:23 UTC, julianbrost requested changes
Version bump for icinga-testing was merged now, so a rebase should make the tests work. Also needed to resolve merge conflicts now.

2022-05-13 11:40 UTC, lippserd commented
> Side note: my personal preference would be putting `AS $$...$$` last (but you don't have to change that).

Mine too, but that leads to syntax errors.

2022-05-13 12:42 UTC, julianbrost commented
Strange, it shouldn't. I mean the SLA function does just that (you can even see the `$$;` in the diff context).

2022-05-13 12:59 UTC, lippserd commented
> Strange, it shouldn't. I mean the SLA function does just that (you can even see the `$$;` in the diff context).

Maybe I was just missing a semicolon then. I'll give it another try!

2022-05-13 13:03 UTC, lippserd commented
> > Strange, it shouldn't. I mean the SLA function does just that (you can even see the `$$;` in the diff context).
> 
> Maybe I was just missing a semicolon then. I'll give it another try!

Works with your layout!

2022-05-13 13:49 UTC, julianbrost approved these changes
Let's see for how long this workaround will live on. (I'd say pretty long, but please do prove me wrong!)

2022-05-13 14:17 UTC, merged