Add environment_id to indices for history retention
Icinga/icingadb pull request #499
Opened 2022-06-15 12:39 UTC by yhabteab

When UPSERT and DELETE statements are executed at the same time, a
deadlock can occur if both want to get an exclusive lock on one of the
PRIMARY KEY index pages. This happens with DELETE statements when there
is no suitable index for the columns used in the WHERE clause, which is
true for our history retention queries since commit https://github.com/Icinga/icingadb/commit/eccac78ff31186430a33d65d286eb91ad7d20d05. This PR
fixes the problem by adding a suitable index for the columns used in
these queries.

fixes #485

2022-06-15 15:12 UTC, julianbrost requested changes
Looks like this was somewhat inconsistent before already, so not the fault of this PR, but probably each of the following tables should have an index on `(environment_id, $Column)`:
https://github.com/Icinga/icingadb/blob/8f31ac143875498797725adb9bfacf3d4f64ede2/pkg/icingadb/history/retention.go#L28-L93

Looks like those are missing for `notification` and `sla_history_downtime`, see:
* `grep 'INDEX.*history.*environment_id' schema/mysql/schema.sql`
* `grep 'CREATE INDEX.*history.*environment_id' schema/pgsql/schema.sql`

2022-06-17 08:39 UTC, julianbrost requested changes
Regarding naming: looks like we don't really follow a consistent pattern there, using (just) the first column in the name seems a common choice, so probably fine.

2022-06-17 08:39 UTC, julianbrost commented on schema/pgsql/schema.sql
> +COMMENT ON INDEX idx_notification_history_environment_id IS 'Filter for sla history retention';
This table is not related to SLA.

2022-06-24 07:34 UTC, julianbrost requested changes
That's not what I tried to say with that pattern. They should be named `idx_notification_history_env_send_time` for example.

2022-06-24 13:08 UTC, lippserd requested changes

2022-06-24 13:08 UTC, lippserd commented on schema/mysql/schema.sql
> +  INDEX idx_downtime_history_end_time (end_time) COMMENT 'Downtime history filtered/ordered by end_time',
This index is free to remove. Web does not provide such a view.

2022-06-24 13:08 UTC, lippserd commented on schema/mysql/schema.sql
> +  INDEX idx_state_history_event_time (event_time) COMMENT 'State history filtered/ordered by event_time',
This index is free to remove. Web does not provide such a view.

2022-06-24 13:08 UTC, lippserd commented on schema/mysql/schema.sql
> +  INDEX idx_comment_history_remove_time (remove_time) COMMENT 'Comment history filtered/ordered by remove_time',
This index is free to remove. Web does not provide such a view.

2022-06-24 13:08 UTC, lippserd commented on schema/mysql/schema.sql
> +  INDEX idx_flapping_history_end_time (end_time) COMMENT 'Flapping history filtered/ordered by end_time',
This index is free to remove. Web does not provide such a view.

2022-06-24 13:08 UTC, lippserd commented on schema/mysql/schema.sql
> +  INDEX idx_acknowledgement_history_clear_time (clear_time) COMMENT 'Acknowledgement history filtered/ordered by clear_time',
This index is free to remove. Web does not provide such a view.

2022-06-28 14:33 UTC, lippserd approved these changes

2022-06-28 14:58 UTC, julianbrost requested changes
Now has a merge conflict that has to be resolved.

2022-06-28 15:29 UTC, julianbrost requested changes
Schema upgrade does not produce the same schema as the full schema file:

```diff
@@ -1583,7 +1584,7 @@
   `downtime_end` bigint unsigned NOT NULL COMMENT 'end time of the downtime',
   PRIMARY KEY (`downtime_id`),
   KEY `idx_sla_history_downtime_event` (`host_id`,`service_id`,`downtime_start`,`downtime_end`) COMMENT 'Filter for calculating the sla reports',
-  KEY `idx_sla_history_downtime_env_downtime_end` (`environment_id`,`downtime_end`) COMMENT 'Filter for sla history retention'
+  KEY `idx_sla_history_downtime_env_event_time` (`environment_id`,`downtime_end`) COMMENT 'Filter for sla history retention'
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;
 /*!40101 SET character_set_client = @saved_cs_client */;
```

2022-06-29 08:53 UTC, julianbrost approved these changes

2022-06-29 08:53 UTC, merged