schema: Add new index for `customvar_flat`
Icinga/icingadb pull request #617
Opened 2023-07-11 07:31 UTC by nilmerg

resolves #523

postgres changes still tbd

2023-07-11 07:34 UTC, nilmerg commented
This is required, because https://github.com/Icinga/ipl-orm/pull/110 will change how Icinga DB Web filters custom variables. Without an index, the then not dependent subqueries will perform a full table scan.

I also played around with just an index on `flatname`, but that turned out to be ignored as the `flatname, flatvalue` index was still being preferred.

2023-08-01 14:19 UTC, Al2Klimov requested changes
New files names don't match PR milestone.

2023-08-01 14:23 UTC, julianbrost commented
There are no new files. It's mixed up already and will be cleaned up with #602, including the schema version.

2023-08-01 14:33 UTC, julianbrost commented on schema/pgsql/schema.sql
> +CREATE INDEX idx_customvar_flat_flatname_flatvalue ON customvar_flat(flatname, flatvalue);
Indeed. I tested with a 32k character long `flatvalue`, PostgreSQL was happy.

2023-08-01 14:36 UTC, merged