MySQL/MariaDB: Use strict SQL mode
Icinga/icingadb pull request #699
Opened 2024-03-18 08:59 UTC by lippserd

For MySQL (and MariaDB, etc.), in addition to `ANSI_QUOTES` SQL mode, we now also set `TRADITIONAL`, which enables strict mode.

refs #624

2024-03-18 14:23 UTC, julianbrost requested changes
Looks like the MySQL tests are failing rightfully, in the `mysql-debug.log.xz` artifact, there are multiple occurrences of this error:

> 2024-03-18T12:28:52.624Z\tFATAL\ticingadb\tError 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

And for the PostgreSQL tests, well, wait a few minutes, I'll create a PR, d'oh! :see_no_evil:

2024-03-18 15:41 UTC, julianbrost commented
> And for the PostgreSQL tests, well, wait a few minutes, I'll create a PR, d'oh! 🙈

Here we go:
* #709

2024-03-19 08:53 UTC, lippserd commented
> Looks like the MySQL tests are failing rightfully, in the `mysql-debug.log.xz` artifact, there are multiple occurrences of this error:
> 
> > 2024-03-18T12:28:52.624Z\tFATAL\ticingadb\tError 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

Yeah, forgot to quote the `sql_mode`.

2024-03-20 10:31 UTC, yhabteab approved these changes
LFTM!

2024-03-21 14:49 UTC, julianbrost approved these changes

2024-03-21 14:49 UTC, merged