Make structifyStream() channel types more explicit, e.g. input only
Icinga/icingadb pull request #797
Opened 2024-09-04 15:11 UTC by Al2Klimov

This enforces which side (caller/function) can read and especially    close/write to a particular channel at compile time.    That leaves less room for bugs (which had to be detected by tests otherwise).

2024-09-06 08:00 UTC, oxzi commented on pkg/icingadb/runtime_updates.go
> +	upserted <-chan database.Entity, deleteIds chan<- any, deleted <-chan any, structifier structify.MapStructifier,
The parameter list got quite long and is imo hard to read in its current format. Would you mind reformatting it, having one parameter each line.

2024-09-06 11:21 UTC, oxzi approved these changes

2024-09-06 12:16 UTC, yhabteab commented
I don't understand what this change is supposed to achieve! Previously, nil channels were initialised and immediately closed, and with PR nil channels are assigned to a new closed one. So, which issue is this supposed to fix?

2024-09-09 15:10 UTC, julianbrost commented
> I don't understand what this change is supposed to achieve!

Makes it more clear in the function signature, which channels are used for input and which for output.

> Previously, nil channels were initialised and immediately closed, and with PR nil channels are assigned to a new closed one. So, which issue is this supposed to fix?

That probably became necessary as otherwise, once you assign a channel to `upserted <-chan database.Entity` for example, you can no longer close it using that `<-chan` reference. Therefore, it's assigned to a temporary variable, closed, then assigned to the final variable that no longer allows closing.

2024-10-02 10:05 UTC, lippserd requested changes
Commit and PR description missing.

2024-10-23 14:43 UTC, merged